RM := rm -rf
BRIDGE_EXE := studio-mdk-bridge.exe
UV4_EXE := "C:\Keil_v538\UV4\UV4.exe"
UVPROJX_LOC := "D:\nextpilot\rt-thread\bsp\stm32\stm32f103-fire-arbitrary\project.uvprojx"

.PHONY: mdk_all

mdk_all:
	-$(BRIDGE_EXE) --build --uv4-path $(UV4_EXE) $(UVPROJX_LOC)

mdk_clean:
	-@$(RM) *
	@echo 'success'



*.elf: $(wildcard ..)
