# /******************************************************************
#  *      _   __             __   ____   _  __        __
#  *     / | / /___   _  __ / /_ / __ \ (_)/ /____   / /_
#  *    /  |/ // _ \ | |/_// __// /_/ // // // __ \ / __/
#  *   / /|  //  __/_>  < / /_ / ____// // // /_/ // /_
#  *  /_/ |_/ \___//_/|_| \__//_/    /_//_/ \____/ \__/
#  *
#  * Copyright All Reserved © 2015-2023 NextPilot Development Team
#  ******************************************************************/

name: build target2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - documentation/**
      - "**/README.md"
      - "**/README_zh.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - documentation/**
      - "**/README.md"
      - "**/README_zh.md"

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    name: BSP Compilation with More Drivers

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install System Tools
        shell: bash
        run: |
          source tools/ci-install.sh
          pip install -r tools/requirements.txt

      - name: Install Arm ToolChains
        if: ${{ success() }}
        shell: bash
        run: |
          wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.3/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          sudo tar xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -C /opt
          /opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc --version
          echo "RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-10-2020-q4-major/bin" >> $GITHUB_ENV

      - name: Install RT-Thread ENV
        shell: bash
        run: |
          git fetch origin
          cd rt-thread
          python -c "import tools.menuconfig; tools.menuconfig.touch_env()"
          cd ..

      - name: Bsp Scons Compile
        if: ${{ success() }}
        shell: bash
        run: |
          pwd
          # git remote -v
          # source ~/.env/env.sh
          # scons
          #python tools/ci/compile_bsp_with_drivers.py
